# Generated by Django 2.1.7 on 2020-02-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0152_auto_20200127_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='название')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='описание')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='телефон')),
                ('managers', models.CharField(blank=True, help_text='Можно несколько через запятую', max_length=255, verbose_name='менеджеры заказов')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.City', verbose_name='город')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'профиль сайта',
                'verbose_name_plural': 'профили сайтов',
            },
        ),
    ]
