# Generated by Django 2.2.27 on 2022-03-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sewingworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='order_prefix',
            field=models.CharField(blank=True, max_length=10, verbose_name='префикс заказов'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sites.Site'),
        ),
    ]
