# Generated by Django 2.2.27 on 2022-03-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewingworld', '0002_auto_20220325_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteprofile',
            old_name='managers',
            new_name='manager_emails',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='manager_phones',
            field=models.CharField(blank=True, help_text='Можно несколько через запятую', max_length=255, verbose_name='телефоны менеджеров'),
        ),
    ]
