# Generated by Django 3.2.12 on 2022-11-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewingworld', '0004_auto_20221117_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='category_root_slug',
            field=models.CharField(blank=True, max_length=30, verbose_name='slug корневой категории'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='product_small_thumbnail_size',
            field=models.PositiveSmallIntegerField(default=80, verbose_name='размер супермалого изображения товара'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='product_thumbnail_size',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='размер малого изображения товара'),
        ),
    ]
