# Generated by Django 3.2.12 on 2022-11-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewingworld', '0005_auto_20221119_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='revalidation_token',
            field=models.CharField(blank=True, max_length=30, verbose_name='Токен перегенерации'),
        ),
    ]
