# Generated by Django 3.2.12 on 2022-12-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewingworld', '0006_siteprofile_revalidation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Указывается на сайте для связи', max_length=255, verbose_name='телефон'),
        ),
    ]
