# Generated by Django 3.2.12 on 2026-01-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewingworld', '0008_siteprofile_wholesale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='product_small_thumbnail_size',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='product_thumbnail_size',
        ),
    ]
