# Generated by Django 4.2.18 on 2026-08-02 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0256_product_sites'),
        ('sewingworld', '0009_auto_20260116_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='root_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='shop.category', verbose_name='корневая категория'),
        ),
    ]
