# Generated by Django 4.2.18 on 2026-08-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewingworld', '0010_siteprofile_root_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='category_root_slug',
        ),
    ]
