# Generated by Django 4.2.18 on 2026-08-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewingworld', '0011_remove_siteprofile_category_root_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
