# Generated by Django 4.2.18 on 2026-08-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewingworld', '0012_alter_siteprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='yookassa_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID аккаунта ЮKassa'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='yookassa_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='секретный ключ ЮKassa'),
        ),
    ]
