version: "3"
name: singer
services:
  app:
    container_name: nextjs-singer
    image: singer
    build:
      context: ./
      target: runner
      args:
        entity: singer
      tags:
        - singer
    volumes:
      - ./.docker/:/app/.docker/
    network_mode: bridge
    ports:
      - "127.0.0.1:4102:3000/tcp"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        syslog-address: unixgram:///run/systemd/journal/dev-log
        tag: "{{.Name}}/{{.ID}}"
