INSTALLED_APPS = (
    'corsheaders',
    'flags',
    'datetimewidget',
    'colorfield',
    'loginas',
    'daterangefilter',
    'mptt',
    'sekizai',  # required for wiki
    'adminsortable2',
    'widget_tweaks',
    'django_better_admin_arrayfield',
    'django_admin_listfilter_dropdown',
    'massadmin',
    'import_export',
    'django_nyt',
    # 'django_clear_memcache',
    # 'cache_cleaner',

    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    'two_factor.plugins.phonenumber',

    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.flatpages',
    'rest_framework',
    'rest_framework.authtoken',
    # 'drf_api_logger',
    'sewingworld.apps.SWAppConfig',
    'sewingworld.apps.SWAdminConfig',
    'django_prometheus',
    'django_celery_beat',
    'django_celery_results',
    # 'django_ipgeobase',
    'django_comments',
    'sorl.thumbnail',  # required for wiki
    'django_filters',
    'tagulous',
    'wiki.apps.WikiConfig',
    'wiki.plugins.attachments.apps.AttachmentsConfig',
    'wiki.plugins.notifications.apps.NotificationsConfig',
    'wiki.plugins.images.apps.ImagesConfig',
    'wiki.plugins.macros.apps.MacrosConfig',
    'shop',
    'beru',
    'sber',
    'ozon',
    'wb',
    'yandex_kassa',
    'reviews',
    'blog',
    'forum',
    'djconfig',
    'django_cleanup',
)
