MIDDLEWARE = (
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'sewingworld.middleware.BlockedIpMiddleware',
    'sewingworld.middleware.RequireStaffMiddleware',
    'sewingworld.middleware.SiteDetectionMiddleware',
    #'sewingworld.middleware.ProcessExceptionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'sewingworld.middleware.SessionCookieMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.common.BrokenLinkEmailsMiddleware',
    'sewingworld.middleware.CsrfCookieMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'djconfig.middleware.DjConfigMiddleware',
    # 'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
)
