# Generated by Django 3.2.12 on 2023-03-29 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(help_text='Используется для формирования URL', max_length=255, unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.SlugField(help_text='Используется для формирования URL', max_length=255, unique_for_date='publication_date', verbose_name='слаг')),
                ('status', models.IntegerField(choices=[(1, 'черновик'), (2, 'спрятанная'), (99, 'опубликована')], db_index=True, default=1, verbose_name='статус')),
                ('publication_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Используется для формирования URL', verbose_name='дата публикации')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, height_field='image_height', upload_to='blog', verbose_name='изображение', width_field='image_width')),
                ('image_width', models.IntegerField(null=True)),
                ('image_height', models.IntegerField(null=True)),
                ('image_caption', models.TextField(blank=True, verbose_name='подпись')),
                ('featured', models.BooleanField(default=False, verbose_name='популярная')),
                ('tags', tagging.fields.TagField(blank=True, max_length=255, verbose_name='тэги')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('categories', models.ManyToManyField(blank=True, related_name='entries', to='blog.Category', verbose_name='категории')),
                ('related', models.ManyToManyField(blank=True, related_name='_blog_entry_related_+', to='blog.Entry', verbose_name='связанные записи')),
                ('sites', models.ManyToManyField(db_index=True, to='sites.Site', verbose_name='сайты')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
                'ordering': ['-publication_date'],
            },
        ),
    ]
