# Generated by Django 3.2.12 on 2026-04-22 15:57

from django.db import migrations


def copy_tags(apps, schema_editor):
    from tagging.utils import parse_tag_input
    model = apps.get_model('blog', 'Entry')
    for obj in model.objects.all():
        obj.tags_new = parse_tag_input(obj.tags)
        obj.save()


def clean_tags(apps, schema_editor):
    from tagging.utils import parse_tag_input
    model = apps.get_model('blog', 'Entry')
    for obj in model.objects.all():
        obj.tags_new.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20260422_1855'),
    ]

    operations = [
        migrations.RunPython(copy_tags, reverse_code=clean_tags)
    ]
