# Generated by Django 3.2.12 on 2026-04-22 16:46

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_entry_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tagulous_Entry_tags_new',
            new_name='Tagulous_Entry_tags',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='tags_new',
            new_name='tags',
        ),
    ]
