# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_courier_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='products', related_query_name='product', to='shop.Category', verbose_name='категории'),
        ),
    ]
