# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_order_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_factor',
            field=models.SmallIntegerField(default=1, verbose_name='Количество в упаковке'),
        ),
        migrations.AddField(
            model_name='product',
            name='ws_code',
            field=models.ForeignKey(default=810, on_delete=django.db.models.deletion.PROTECT, related_name='wsprice', to='shop.Currency', verbose_name='опт. валюта'),
        ),
        migrations.AddField(
            model_name='product',
            name='ws_max_discount',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='опт. макс. скидка, %'),
        ),
        migrations.AddField(
            model_name='product',
            name='ws_pack_only',
            field=models.BooleanField(default=False, verbose_name='опт. только упаковкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='ws_price',
            field=models.PositiveIntegerField(default=0, verbose_name='опт. цена, вал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cur_code',
            field=models.ForeignKey(default=810, on_delete=django.db.models.deletion.PROTECT, related_name='rtprice', to='shop.Currency', verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spprice',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена СП, вал'),
        ),
    ]
