# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_auto_20170710_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='basset_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='id в Бассет'),
        ),
    ]
