# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_auto_20170712_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spprice',
            new_name='sp_price',
        ),
        migrations.AddField(
            model_name='product',
            name='sp_code',
            field=models.ForeignKey(default=643, on_delete=django.db.models.deletion.PROTECT, related_name='spprice', to='shop.Currency', verbose_name='СП валюта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cur_code',
            field=models.ForeignKey(default=643, on_delete=django.db.models.deletion.PROTECT, related_name='rtprice', to='shop.Currency', verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ws_code',
            field=models.ForeignKey(default=643, on_delete=django.db.models.deletion.PROTECT, related_name='wsprice', to='shop.Currency', verbose_name='опт. валюта'),
        ),
    ]
