# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_auto_20170717_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_wholesale',
            field=models.BooleanField(default=False),
        ),
    ]
