# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_shopuser_is_wholesale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ws_code',
            new_name='ws_cur_code',
        ),
        migrations.AddField(
            model_name='product',
            name='ws_cur_price',
            field=models.PositiveIntegerField(default=0, verbose_name='опт. цена, вал'),
        ),
        migrations.AddField(
            model_name='product',
            name='ws_pct_discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='опт. скидка, %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ws_price',
            field=models.PositiveIntegerField(default=0, verbose_name='опт. цена, руб'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='скидка, %'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активный'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='админ'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='сотрудник'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='is_wholesale',
            field=models.BooleanField(default=False, verbose_name='оптовик'),
        ),
    ]
