# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_auto_20170723_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sp_code',
            new_name='sp_cur_code',
        ),
        migrations.AddField(
            model_name='product',
            name='sp_cur_price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена СП, вал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sp_price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена СП, руб'),
        ),
    ]
