# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_auto_20170811_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='promo_image',
            field=models.ImageField(blank=True, upload_to='categories', verbose_name='промо изображение'),
        ),
    ]
