# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_auto_20170814_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='promo_image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='promo_image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='categories', verbose_name='изображение', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='category',
            name='promo_image',
            field=models.ImageField(blank=True, height_field='promo_image_height', upload_to='categories', verbose_name='промо изображение', width_field='promo_image_width'),
        ),
    ]
