# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-25 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_auto_20171221_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='GTIN'),
        ),
    ]
