# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-31 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_auto_20171225_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена товара'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='val_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='скидка, руб'),
        ),
        migrations.AlterField(
            model_name='product',
            name='consultant_delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Стоимость доставки с консультантом'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cur_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена, вал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='oprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена розничная'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена, руб'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sp_cur_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена СП, вал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sp_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена СП, руб'),
        ),
        migrations.AlterField(
            model_name='product',
            name='val_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='скидка, руб'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ws_cur_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='опт. цена, вал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ws_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='опт. цена, руб'),
        ),
    ]
