# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-08 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_auto_20180131_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='SN'),
        ),
    ]
