# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-08 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_orderitem_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_size_height',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_size_length',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='длина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_size_width',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ширина'),
        ),
    ]
