# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_auto_20180208_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='val_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='скидка, руб'),
        ),
    ]
