# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-14 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_auto_20180208_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата отправки'),
        ),
    ]
