# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-14 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_order_dispatch_date'),
    ]

    operations = [
        migrations.RenameField('Order', 'delivery_date', 'delivery_dispatch_date'),
    ]
