# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_auto_20180214_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_dispatch_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата отправки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_handing_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата получения'),
        ),
    ]
