# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_auto_20180219_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Country')),
            ],
            options={
                'verbose_name_plural': 'регионы',
                'verbose_name': 'регион',
            },
        ),
    ]
