# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-19 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='телефон')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('enabled', models.BooleanField(default=True, verbose_name='включён')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('latitude', models.FloatField(blank=True, default=0, null=True, verbose_name='широта')),
                ('longitude', models.FloatField(blank=True, default=0, null=True, verbose_name='долгота')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='индекс')),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name='адрес')),
                ('phone2', models.CharField(blank=True, max_length=100, verbose_name='телефон')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='сайт')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='эл.адрес')),
                ('hours', models.CharField(blank=True, max_length=100, verbose_name='раб.часы')),
                ('logo', models.CharField(blank=True, max_length=30, verbose_name='логотип')),
                ('payment_cash', models.BooleanField(default=False, verbose_name='наличные')),
                ('payment_visa', models.BooleanField(default=False, verbose_name='visa')),
                ('payment_master', models.BooleanField(default=False, verbose_name='mastercard')),
                ('payment_mir', models.BooleanField(default=False, verbose_name='мир')),
                ('payment_credit', models.BooleanField(default=False, verbose_name='кредит')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.City')),
            ],
        ),
    ]
