# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0075_auto_20180219_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.SmallIntegerField(choices=[(1, 'похожий'), (2, 'аксессуар'), (3, 'подарок')], db_index=True, default=1, verbose_name='тип')),
                ('child_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_products', to='shop.Product')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_products', to='shop.Product')),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('country', 'name'), 'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('city', 'address'), 'verbose_name': 'магазин', 'verbose_name_plural': 'магазины'},
        ),
        migrations.AddField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(through='shop.ProductRelation', to='shop.Product'),
        ),
    ]
