# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-31 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_auto_20180330_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.CharField(max_length=100)),
                ('active', models.BooleanField(verbose_name='активная')),
                ('brief', models.TextField(blank=True, verbose_name='описание')),
                ('description', models.TextField(blank=True, verbose_name='статья')),
                ('image', models.ImageField(blank=True, height_field='image_height', upload_to='actions', verbose_name='изображение', width_field='image_width')),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
            },
        ),
        migrations.AlterField(
            model_name='productrelation',
            name='child_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_products', to='shop.Product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='productrelation',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_products', to='shop.Product', verbose_name='связанный товар'),
        ),
    ]
