# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-31 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_auto_20180331_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_actions',
            field=models.ManyToManyField(related_name='products', related_query_name='product', to='shop.SalesAction', verbose_name='акции'),
        ),
    ]
