# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-31 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_product_sales_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesaction',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
