# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0080_auto_20180402_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.CharField(blank=True, max_length=255, verbose_name='вариации'),
        ),
    ]
