# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0080_auto_20180402_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesaction',
            name='show_products',
            field=models.BooleanField(default=True, verbose_name='показывать список товаров'),
        ),
    ]
