# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0081_auto_20180410_1132'),
        ('shop', '0081_salesaction_show_products'),
    ]

    operations = [
    ]
