# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0082_merge_20180410_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesaction',
            name='show_products',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', upload_to='logos', verbose_name='логотип', width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
