# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-15 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0083_auto_20180414_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesaction',
            name='show_products',
            field=models.BooleanField(default=True, verbose_name='показывать список товаров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_val_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='макс. скидка, руб'),
        ),
    ]
