# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-15 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0084_auto_20180415_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.FileField(blank=True, upload_to='logos', verbose_name='логотип'),
        ),
    ]
