# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0085_auto_20180415_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesaction',
            name='notice',
            field=models.CharField(blank=True, max_length=50, verbose_name='уведомление'),
        ),
        migrations.AddField(
            model_name='salesaction',
            name='sites',
            field=models.ManyToManyField(to='sites.Site', verbose_name='sites'),
        ),
    ]
