# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-20 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0086_auto_20180420_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesaction',
            name='sites',
            field=models.ManyToManyField(to='sites.Site', verbose_name='сайты'),
        ),
    ]
