# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0087_auto_20180420_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='телефон')),
                ('enabled', models.BooleanField(default=True, verbose_name='включён')),
                ('latitude', models.FloatField(blank=True, default=0, null=True, verbose_name='широта')),
                ('longitude', models.FloatField(blank=True, default=0, null=True, verbose_name='долгота')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.City', verbose_name='город')),
            ],
            options={
                'verbose_name_plural': 'сервис-центры',
                'ordering': ('city', 'address'),
                'verbose_name': 'сервис-центр',
            },
        ),
    ]
