# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0088_servicecenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='forbid_spb_price_import',
            field=models.BooleanField(default=False, verbose_name='не импортировать цену СПб'),
        ),
        migrations.AddField(
            model_name='product',
            name='spb_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена СПб, руб'),
        ),
    ]
