# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0089_auto_20180426_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, default=0, max_digits=10, verbose_name='цена, руб'),
        ),
    ]
