# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0090_auto_20180426_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spb_num',
            field=models.SmallIntegerField(default=-1, verbose_name='в наличии СПб'),
        ),
        migrations.AddField(
            model_name='stock',
            name='correction',
            field=models.FloatField(default=0, verbose_name='корректировка'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='count_in_stock',
            field=models.SmallIntegerField(choices=[(99, 'не учитывать'), (1, 'наличие'), (2, 'под заказ')], default=99, verbose_name='учитывать в наличии'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='spb_count_in_stock',
            field=models.SmallIntegerField(choices=[(99, 'не учитывать'), (1, 'наличие'), (2, 'под заказ')], default=99, verbose_name='учитывать в наличии СПб'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num',
            field=models.SmallIntegerField(db_column='num', default=-1, verbose_name='в наличии'),
        ),
    ]
