# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0091_auto_20180515_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ya_active',
            field=models.BooleanField(default=True, verbose_name='выдавать в Яндекс.Маркет'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Supplier', verbose_name='поставщик'),
        ),
    ]
