# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-04 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0093_auto_20180607_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ws_num',
            field=models.SmallIntegerField(default=-1, verbose_name='в наличии Опт'),
        ),
    ]
