# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-01 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0094_product_ws_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.CharField(db_index=True, default='', max_length=17, verbose_name='GTIN'),
        ),
    ]
