# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0097_auto_20180809_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesaction',
            name='show_in_list',
            field=models.BooleanField(default=True, verbose_name='показывать в списке'),
        ),
    ]
