# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-21 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0098_salesaction_show_in_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('active', models.BooleanField(verbose_name='активная')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('order', models.PositiveIntegerField()),
                ('sites', models.ManyToManyField(to='sites.Site', verbose_name='сайты')),
            ],
            options={
                'verbose_name': 'реклама',
                'verbose_name_plural': 'рекламы',
            },
        ),
    ]
