# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models
# import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0101_auto_20180905_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='теги'),
            # field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='теги'),
        ),
    ]
