# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-10 11:04
from __future__ import unicode_literals

from django.db import migrations, models
# import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0102_shopuser_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='теги'),
            # field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='теги'),
        ),
    ]
