# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0104_productset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productset',
            name='recalculate_price',
        ),
        migrations.AddField(
            model_name='product',
            name='constituents',
            field=models.ManyToManyField(blank=True, related_name='_product_constituents_+', through='shop.ProductSet', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='recalculate_price',
            field=models.BooleanField(default=True, verbose_name='пересчитывать цену комплекта'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='constituent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_declarations', to='shop.Product', verbose_name='составляющая'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_constituents', to='shop.Product', verbose_name='определение'),
        ),
    ]
