# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-14 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0105_auto_20180913_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='num_correction',
        ),
        migrations.AlterField(
            model_name='product',
            name='recalculate_price',
            field=models.BooleanField(default=True, verbose_name='пересчитывать цену'),
        ),
    ]
