# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-19 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0106_auto_20180915_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='credit_allowed',
            field=models.BooleanField(default=False, verbose_name='можно в кредит'),
        ),
    ]
