# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-26 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0108_auto_20180925_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('change_order_spb', 'Может редактировать заказы СПб'),), 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='эл.почта'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(max_length=30, unique=True, verbose_name='телефон'),
        ),
    ]
