# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-27 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0110_remove_shopuser_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'permissions': (('wholesale', 'Может покупать оптом'),), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='is_wholesale',
        ),
    ]
