# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0111_auto_20180927_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='кол-во'),
        ),
    ]
