# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0112_productset_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='общ. цена'),
        ),
    ]
