# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-29 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0113_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_contents',
            field=models.BooleanField(default=False, verbose_name='скрыть содержимое'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='сумма'),
        ),
    ]
