# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-29 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0114_auto_20181029_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hide_contents',
            field=models.BooleanField(default=True, verbose_name='скрыть содержимое'),
        ),
    ]
