# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-02 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0116_remove_category_basset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата регистрации'),
        ),
    ]
