# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-16 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0117_shopuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_order',
            field=models.CharField(default='-price', max_length=50, verbose_name='поле сортировки товаров'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='позиция сортировки'),
        ),
    ]
