# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-27 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0118_auto_20181116_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='прозвище'),
        ),
    ]
