# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-28 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0119_shopuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='permanent_password',
            field=models.BooleanField(default=False, verbose_name='постоянный пароль'),
        ),
    ]
