# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-28 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0120_shopuser_permanent_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='active',
            field=models.BooleanField(db_index=True, verbose_name='активная'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='place',
            field=models.CharField(db_index=True, max_length=100, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='sites',
            field=models.ManyToManyField(db_index=True, to='sites.Site', verbose_name='сайты'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='salesaction',
            name='sites',
            field=models.ManyToManyField(db_index=True, to='sites.Site', verbose_name='сайты'),
        ),
        migrations.AlterField(
            model_name='salesaction',
            name='slug',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
