# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0121_auto_20181129_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_reviews',
            field=models.BooleanField(default=True, verbose_name='Разрешить обзоры'),
        ),
    ]
