# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0122_product_allow_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'производитель', 'verbose_name_plural': 'производители'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='ws_count_in_stock',
            field=models.SmallIntegerField(choices=[(99, 'не учитывать'), (1, 'наличие'), (2, 'под заказ')], default=99, verbose_name='учитывать в наличии Опт'),
        ),
    ]
