# Generated by Django 2.1.7 on 2019-04-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0125_auto_20190402_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
