# Generated by Django 2.1.7 on 2019-04-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0126_remove_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num',
            field=models.IntegerField(db_column='num', default=-1, verbose_name='в наличии'),
        ),
    ]
