# Generated by Django 2.1.7 on 2019-04-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0127_auto_20190413_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='internetonly',
        ),
        migrations.AlterField(
            model_name='stock',
            name='correction',
            field=models.FloatField(default=0, verbose_name='коррекция'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='shop.Supplier', verbose_name='склад'),
        ),
    ]
