# Generated by Django 2.1.7 on 2019-06-13 14:55

from django.db import migrations, models
import model_field_list.fields
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0129_auto_20190529_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comparison', model_field_list.fields.ModelFieldListField(blank=True, source_model=shop.models.Product, separator=',', verbose_name='критерии сравнения')),
            ],
            options={
                'verbose_name': 'тип товара',
                'verbose_name_plural': 'типы товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', to='shop.ProductKind', verbose_name='тип'),
        ),
    ]
