# Generated by Django 2.1.7 on 2019-06-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0131_auto_20190614_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='beru',
            field=models.BooleanField(db_index=True, default=False, verbose_name='выгружать в Беру'),
        ),
        migrations.AddField(
            model_name='product',
            name='beru_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена Беру, руб'),
        ),
    ]
