# Generated by Django 2.1.7 on 2019-06-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0132_auto_20190614_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oprice',
        ),
    ]
