# Generated by Django 2.1.7 on 2019-06-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0133_auto_20190614_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='forbid_ws_price_import',
            field=models.BooleanField(default=False, verbose_name='не импортировать опт. цену'),
        ),
    ]
