# Generated by Django 2.1.7 on 2019-08-27 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0136_auto_20190707_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.TextField(verbose_name='object ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='rating')),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='weight')),
                ('submit_date', models.DateTimeField(db_index=True, default=None, verbose_name='submitted at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP address')),
                ('is_public', models.BooleanField(default=False, help_text='Check this box to publish review on the site.', verbose_name='is public')),
                ('comment', models.TextField(blank=True, max_length=3000, verbose_name='комментарий')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_productreview', to='contenttypes.ContentType', verbose_name='content type')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productreview_comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'permissions': [('can_moderate', 'Can moderate reviews')],
                'ordering': ('-submit_date',),
                'abstract': False,
            },
        ),
    ]
