# Generated by Django 2.1.7 on 2019-09-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0137_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'товарная позиция', 'verbose_name_plural': 'товарные позиции'},
        ),
        migrations.AddField(
            model_name='basket',
            name='secondary',
            field=models.BooleanField(default=False),
        ),
    ]
