# Generated by Django 2.1.7 on 2019-10-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0139_auto_20191007_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manuals',
            field=models.TextField(blank=True, verbose_name='инструкции'),
        ),
    ]
