# Generated by Django 2.1.7 on 2019-10-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0138_auto_20190919_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prom_weight',
            field=models.FloatField(default=0, verbose_name='Вес с упаковкой, кг'),
        ),
    ]
