# Generated by Django 2.1.7 on 2019-10-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0139_product_manuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sm_wastebin',
            field=models.CharField(blank=True, max_length=50, verbose_name='мусоросборник'),
        ),
    ]
