# Generated by Django 2.1.7 on 2019-10-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0140_product_sw_wastebin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='количество')),
                ('weight', models.FloatField(default=0, verbose_name='вес, кг')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='длина, см')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ширина, см')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='высота, см')),
            ],
            options={
                'verbose_name_plural': 'товарные позиции',
                'verbose_name': 'товарная позиция',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', related_query_name='box', to='shop.Order'),
        ),
        migrations.AddField(
            model_name='box',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shop.Product', verbose_name='товар'),
        ),
    ]
