# Generated by Django 2.1.7 on 2019-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0141_auto_20191017_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='трек-код'),
        ),
    ]
