# Generated by Django 2.1.7 on 2019-10-18 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0143_auto_20191017_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='product',
        ),
        migrations.RemoveField(
            model_name='box',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='box', to='shop.Box', verbose_name='коробка'),
        ),
    ]
