# Generated by Django 2.1.7 on 2019-10-29 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0146_auto_20191028_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='created',
            field=models.DateField(default=datetime.date.today, verbose_name='дата формирования'),
        ),
        migrations.AlterField(
            model_name='act',
            name='orders',
            field=models.ManyToManyField(db_index=True, related_name='acts', through='shop.ActOrder', to='shop.Order', verbose_name='заказы'),
        ),
    ]
