# Generated by Django 2.1.7 on 2019-11-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0147_auto_20191029_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['id'], 'verbose_name': 'коробка', 'verbose_name_plural': 'коробки'},
        ),
        migrations.AddField(
            model_name='basketitem',
            name='ext_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
