# Generated by Django 2.1.7 on 2019-11-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0148_auto_20191112_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alert',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='тревога'),
        ),
    ]
