# Generated by Django 2.1.7 on 2019-11-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0149_order_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='спрятана'),
        ),
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='включена'),
        ),
    ]
