# Generated by Django 2.1.7 on 2020-02-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0152_auto_20200127_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.SmallIntegerField(choices=[(99, 'уточняется'), (1, 'курьер'), (2, 'консультант'), (3, 'получу сам в магазине'), (4, 'транспортная компания'), (5, 'PickPoint'), (6, 'Яндекс.Доставка'), (7, 'транзит')], db_index=True, default=99, verbose_name='доставка'),
        ),
    ]
