# Generated by Django 2.1.7 on 2020-04-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0153_auto_20200227_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spb_num',
            field=models.IntegerField(default=-1, verbose_name='в наличии СПб'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ws_num',
            field=models.IntegerField(default=-1, verbose_name='в наличии Опт'),
        ),
    ]
