# Generated by Django 2.1.7 on 2020-07-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0154_auto_20200413_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.BooleanField(db_index=True, default=False, verbose_name='мерчант'),
        ),
    ]
