# Generated by Django 2.1.7 on 2021-01-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0156_auto_20210113_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='трек-код'),
        ),
    ]
