# Generated by Django 2.1.7 on 2021-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0157_auto_20210115_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hidden_tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='трек-код'),
        ),
    ]
