# Generated by Django 2.1.7 on 2021-03-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0160_product_taxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='taxi_count_in_stock',
            field=models.SmallIntegerField(choices=[(99, 'не учитывать'), (1, 'наличие'), (2, 'под заказ')], default=99, verbose_name='учитывать в наличии Такси'),
        ),
    ]
