# Generated by Django 2.1.7 on 2021-04-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0161_supplier_taxi_count_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', upload_to='stores', verbose_name='изображение', width_field='image_width')),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('kind', models.CharField(choices=[('exterior', 'экстерьер'), ('interior', 'интерьер'), ('enter', 'вход'), ('logo', 'логотип'), ('goods', 'товары'), ('food', 'блюда, напитки')], default='exterior', max_length=50, verbose_name='тип')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'изображение магазина',
                'verbose_name_plural': 'изображения магазина',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='публиковать в картах'),
        ),
        migrations.AddField(
            model_name='storeimage',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Store'),
        ),
    ]
