# Generated by Django 2.1.7 on 2021-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0162_auto_20210425_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mdbs',
            field=models.BooleanField(db_index=True, default=False, verbose_name='выгружать в Маркет.DBS'),
        ),
    ]
