# Generated by Django 2.1.7 on 2021-08-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0165_auto_20210615_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ali',
            field=models.BooleanField(db_index=True, default=False, verbose_name='выгружать в Али'),
        ),
        migrations.AddField(
            model_name='product',
            name='ali_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена Али, руб'),
        ),
    ]
