# Generated by Django 2.1.7 on 2021-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0166_auto_20210815_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax2',
            field=models.BooleanField(db_index=True, default=False, verbose_name='выгружать в Яндекс.Такси СПб'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax2_count_in_stock',
            field=models.SmallIntegerField(choices=[(99, 'не учитывать'), (1, 'наличие'), (2, 'под заказ')], default=99, verbose_name='учитывать в наличии Такси СПб'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'новый заказ'), (1, 'принят в работу'), (4, 'комплектуется'), (8, 'отменен'), (16, 'заморожен'), (32, 'передан в другой магазин'), (64, 'собран'), (128, 'сервис'), (1024, 'доставляется'), (2048, 'доставлен'), (256, 'доставлен в магазин'), (512, 'передан в службу доставки'), (4096, 'консультация'), (8192, 'проблема'), (33554432, 'возвращается'), (67108864, 'не востребован'), (16384, 'завершён'), (251658240, 'выполнен')], db_index=True, default=0, verbose_name='статус'),
        ),
    ]
