# Generated by Django 2.1.7 on 2021-10-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0168_auto_20210929_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='bonuses',
            field=models.PositiveIntegerField(default=0, verbose_name='бонусы'),
        ),
    ]
