# Generated by Django 2.1.7 on 2021-12-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0172_auto_20211124_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax3',
            field=models.BooleanField(db_index=True, default=False, verbose_name='выгружать в Яндекс.Такси НН'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax3_count_in_stock',
            field=models.SmallIntegerField(choices=[(99, 'не учитывать'), (1, 'наличие'), (2, 'под заказ')], default=99, verbose_name='учитывать в наличии Такси НН'),
        ),
    ]
