# Generated by Django 2.1.7 on 2022-02-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0173_auto_20211207_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='expiration_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='дата сгорания бонусов'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='expiring_bonuses',
            field=models.PositiveIntegerField(default=0, verbose_name='сгорающие бонусы'),
        ),
    ]
