# Generated by Django 2.1.7 on 2022-02-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0174_auto_20220209_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата сгорания бонусов'),
        ),
    ]
