# Generated by Django 2.1.7 on 2022-03-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0177_auto_20220324_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('utm_source', models.CharField(max_length=20, verbose_name='источник')),
                ('uses_api', models.BooleanField(default=False, verbose_name='использует API')),
            ],
            options={
                'verbose_name': 'интеграция',
                'ordering': ['name'],
                'verbose_name_plural': 'интеграции',
            },
        ),
        migrations.CreateModel(
            name='ProductIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена, руб')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Integration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in_stock', models.SmallIntegerField(choices=[(99, 'не учитывать'), (1, 'наличие'), (2, 'под заказ')], default=99, verbose_name='учитывать в наличии')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Integration')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Supplier', verbose_name='поставщик')),
            ],
        ),
        migrations.AddField(
            model_name='integration',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='integrations', related_query_name='integration', through='shop.ProductIntegration', to='shop.Product', verbose_name='выгружаемые товары'),
        ),
        migrations.AddField(
            model_name='integration',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='сайт'),
        ),
    ]
