# Generated by Django 2.2.27 on 2022-03-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0178_auto_20220324_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Integration', verbose_name='интеграция'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='integrations', related_query_name='integration', through='shop.ProductIntegration', to='shop.Product'),
        ),
    ]
