# Generated by Django 2.2.27 on 2022-03-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0181_integration_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ali_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='avito_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='beru_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sber_price',
        ),
        migrations.AddField(
            model_name='integration',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='integrations', related_query_name='integration', to='shop.Supplier', verbose_name='поставщик'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrations', related_query_name='integration', to='sites.Site', verbose_name='сайт'),
        ),
        migrations.DeleteModel(
            name='SupplierIntegration',
        ),
    ]
