# Generated by Django 2.2.27 on 2022-03-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0183_auto_20220327_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='output_available',
            field=models.BooleanField(default=False, verbose_name='выгражать только в наличии'),
        ),
        migrations.AddField(
            model_name='integration',
            name='output_template',
            field=models.CharField(default='products', max_length=20, verbose_name='шаблон выгрузки'),
            preserve_default=False,
        ),
    ]
