# Generated by Django 2.2.27 on 2022-03-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0184_auto_20220328_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='output_stock',
            field=models.BooleanField(default=False, verbose_name='выгражать остатки'),
        ),
    ]
