# Generated by Django 3.2.12 on 2022-05-15 18:19

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0186_auto_20220330_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='meta',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='courier',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='integration',
            name='admin_user_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='поля покупателя'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='settings',
            field=models.JSONField(blank=True, null=True, verbose_name='настройки'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='meta',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'новый заказ'), (1, 'принят в работу'), (2, 'ожидает подтверждения'), (4, 'комплектуется'), (8, 'отменен'), (16, 'заморожен'), (32, 'передан в другой магазин'), (64, 'собран'), (128, 'сервис'), (1024, 'доставляется'), (2048, 'доставлен'), (256, 'доставлен в магазин'), (512, 'передан в службу доставки'), (4096, 'консультация'), (8192, 'проблема'), (33554432, 'возвращается'), (67108864, 'не востребован'), (16384, 'завершён'), (251658240, 'выполнен')], db_index=True, default=0, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='meta',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
