# Generated by Django 3.2.12 on 2022-05-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0188_auto_20220517_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='reviewer_avatar',
            field=models.CharField(blank=True, max_length=255, verbose_name='аватар пользователя'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='имя пользователя'),
        ),
    ]
