# Generated by Django 3.2.12 on 2022-09-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0191_auto_20220902_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.SmallIntegerField(choices=[(99, 'уточняется'), (1, 'курьер'), (2, 'консультант'), (3, 'получу сам в магазине'), (4, 'транспортная компания'), (8, 'почта России'), (9, 'OZON'), (5, 'PickPoint'), (10, 'Интеграл'), (11, 'Boxberry'), (6, 'Яндекс.Доставка'), (7, 'транзит'), (98, 'экспресс')], db_index=True, default=99, verbose_name='доставка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_notes',
            field=models.CharField(blank=True, max_length=128, verbose_name='Yandex.Market Sales Notes'),
        ),
    ]
