# Generated by Django 3.2.12 on 2022-11-09 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0194_auto_20221109_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('image', models.ImageField(blank=True, height_field='image_height', upload_to='news', verbose_name='изображение', width_field='image_width')),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(verbose_name='содержимое')),
                ('active', models.BooleanField(db_index=True, verbose_name='активная')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('sites', models.ManyToManyField(db_index=True, to='sites.Site', verbose_name='сайты')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['publish_date'],
            },
        ),
    ]
