# Generated by Django 3.2.12 on 2023-02-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0197_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='output_all',
            field=models.BooleanField(default=False, help_text='Выгружать товары по дереву категорий, а не по флагу интеграции', verbose_name='выгражать все'),
        ),
    ]
