# Generated by Django 3.2.12 on 2023-02-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0200_order_wirehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.contractor', verbose_name='покупатель 1С по-умолчанию'),
        ),
        migrations.AddField(
            model_name='integration',
            name='wirehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.supplier', verbose_name='склад отгрузки по-умолчанию'),
        ),
    ]
