# Generated by Django 3.2.12 on 2023-02-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0201_auto_20230206_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='is_default_seller',
            field=models.BooleanField(default=False, verbose_name='продавец по-умолчанию'),
        ),
    ]
