# Generated by Django 3.2.12 on 2023-02-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0202_contractor_is_default_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='show_in_list',
            field=models.BooleanField(db_index=True, default=False, verbose_name='показывать в списках'),
        ),
    ]
