# Generated by Django 3.2.12 on 2023-02-09 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0203_supplier_show_in_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='wirehouse',
            field=models.ForeignKey(blank=True, limit_choices_to={'show_in_list': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.supplier', verbose_name='склад отгрузки по-умолчанию'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wirehouse',
            field=models.ForeignKey(blank=True, limit_choices_to={'show_in_list': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.supplier', verbose_name='склад отгрузки'),
        ),
    ]
