# Generated by Django 3.2.12 on 2023-02-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0204_auto_20230209_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
            preserve_default=False,
        ),
    ]
