# Generated by Django 3.2.12 on 2023-03-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0205_basket_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='forbid_spb_price_import',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spb_market',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spb_num',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spb_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spb_show_in_catalog',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ws_num',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='spb_count_in_stock',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='ws_count_in_stock',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'новый заказ'), (1, 'принят в работу'), (2, 'ожидает подтверждения'), (4, 'комплектуется'), (8, 'отменен'), (16, 'заморожен'), (32, 'передан в другой магазин'), (64, 'собран'), (128, 'сервис'), (1024, 'доставляется'), (2048, 'доставлен'), (256, 'доставлен в магазин'), (512, 'передан в службу доставки'), (4096, 'консультация'), (8192, 'проблема'), (33554432, 'возвращается'), (67108864, 'не востребован'), (16384, 'завершён'), (251658240, 'выполнен')], db_index=True, default=0, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='market',
            field=models.BooleanField(db_index=True, default=False, verbose_name='маркет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num',
            field=models.IntegerField(default=-1, verbose_name='в наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='цена, руб'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_on_sw',
            field=models.BooleanField(db_index=True, default=True, verbose_name='витрина'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='express_count_in_stock',
            field=models.SmallIntegerField(choices=[(99, 'не учитывать'), (1, 'наличие'), (2, 'под заказ')], default=99, verbose_name='учитывать в наличии Экспресс'),
        ),
    ]
