# Generated by Django 3.2.12 on 2023-03-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0206_auto_20230329_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ['id']},
        ),
    ]
