# Generated by Django 3.2.12 on 2023-10-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0211_alter_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='output_with_images',
            field=models.BooleanField(default=False, verbose_name='выгражать только с картинками'),
        ),
    ]
