# Generated by Django 3.2.12 on 2023-11-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0212_integration_output_with_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment_packer',
            field=models.CharField(blank=True, max_length=255, verbose_name='комментарий для сборщика'),
        ),
    ]
