# Generated by Django 3.2.12 on 2024-02-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0214_auto_20231225_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.contractor', verbose_name='продавец 1С по-умолчанию'),
        ),
    ]
