# Generated by Django 3.2.12 on 2024-02-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0216_alter_integration_utm_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='is_default_seller',
        ),
    ]
