# Generated by Django 3.2.12 on 2024-03-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0217_remove_contractor_is_default_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='script',
            field=models.ImageField(blank=True, upload_to='contractors', verbose_name='подпись'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='stamp',
            field=models.ImageField(blank=True, upload_to='contractors', verbose_name='печать'),
        ),
    ]
