# Generated by Django 3.2.12 on 2024-03-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0218_auto_20240304_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='yookassa_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID аккаунта ЮKassa'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='yookassa_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='секретный ключ ЮKassa'),
        ),
    ]
