# Generated by Django 3.2.12 on 2024-03-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0219_auto_20240304_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosTerminal',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='идентификатор кассы')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.contractor')),
            ],
            options={
                'verbose_name': 'pos-терминал',
                'verbose_name_plural': 'pos-терминалы',
            },
        ),
    ]
