# Generated by Django 3.2.12 on 2024-03-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0220_posterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='modulkassa_login',
            field=models.CharField(blank=True, max_length=255, verbose_name='логин МодульКасса'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='modulkassa_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='пароль МодульКасса'),
        ),
    ]
