# Generated by Django 3.2.12 on 2024-03-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0221_auto_20240313_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='pos_terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.posterminal', verbose_name='pos-терминал'),
        ),
        migrations.AlterField(
            model_name='posterminal',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.contractor', verbose_name='продавец'),
        ),
    ]
