# Generated by Django 3.2.12 on 2024-03-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0222_auto_20240313_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='pos_id',
        ),
    ]
