# Generated by Django 3.2.12 on 2024-03-18 13:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0223_remove_courier_pos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), db_index=True, default=list, size=None, verbose_name='Дополнительные штих-коды'),
            preserve_default=False,
        ),
    ]
