# Generated by Django 3.2.12 on 2024-03-24 09:40

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0225_auto_20240318_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gtins',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, db_index=True, default=list, size=None, verbose_name='дополнительные штих-коды'),
        ),
    ]
