# Generated by Django 3.2.12 on 2024-04-16 13:01

from django.db import migrations, models
import shop.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0227_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='big_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=shop.models.product.product_big_image_path, verbose_name='большое изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=shop.models.product.product_image_path, verbose_name='изображение'),
        ),
    ]
