# Generated by Django 3.2.12 on 2024-04-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0228_auto_20240416_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_prefix',
        ),
    ]
