# Generated by Django 3.2.12 on 2024-05-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0229_remove_product_image_prefix'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_fts_vec_b7da43_gin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fts_vector',
        ),
    ]
