# Generated by Django 3.2.12 on 2024-08-06 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0230_auto_20240529_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='SN')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='дата покупки')),
                ('approved', models.BooleanField(default=False, verbose_name='проверен')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий менеджера')),
            ],
            options={
                'verbose_name': 'гарантийный талон',
                'verbose_name_plural': 'гарантийные талоны',
                'ordering': ['-purchase_date', 'number'],
            },
        ),
        migrations.AddField(
            model_name='serial',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shop.order', verbose_name='заказ'),
        ),
        migrations.AddField(
            model_name='serial',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shop.product', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='serial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
