# Generated by Django 3.2.12 on 2024-08-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0230_auto_20240807_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='shop.order', verbose_name='заказ'),
        ),
    ]
