# Generated by Django 3.2.12 on 2024-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0231_auto_20240820_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='feed',
            field=models.BooleanField(default=True, verbose_name='выдавать в фиды'),
        ),
    ]
