# Generated by Django 3.2.12 on 2024-08-28 08:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0231_auto_20240820_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fts_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fts_vector'], name='shop_produc_fts_vec_b7da43_gin'),
        ),
    ]
