# Generated by Django 3.2.12 on 2024-09-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0232_auto_20240913_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='marketplace',
            field=models.BooleanField(default=False, verbose_name='участник акции с маркетплейсами'),
        ),
    ]
