# Generated by Django 3.2.12 on 2024-10-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0233_auto_20240926_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lottery',
            field=models.BooleanField(default=False, verbose_name='участник лотереи'),
        ),
    ]
