# Generated by Django 3.2.12 on 2024-12-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0234_auto_20241014_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='tax_system',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'ОСН'), (2, 'УСН')], null=True, verbose_name='система налогообложения'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='vat_rate',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Без НДС'), (2, 'НДС по ставке 0%'), (7, 'НДС по ставке 5%'), (8, 'НДС по ставке 7%'), (3, 'НДС по ставке 10%'), (4, 'НДС чека по ставке 20%')], null=True, verbose_name='ставка НДС'),
        ),
    ]
