# Generated by Django 3.2.12 on 2025-01-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0235_auto_20241227_1513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productintegration',
            unique_together={('product', 'integration')},
        ),
    ]
