# Generated by Django 3.2.12 on 2025-01-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0236_auto_20250110_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ya_active',
        ),
    ]
