# Generated by Django 3.2.12 on 2025-03-02 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0239_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_actions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, related_name='products', related_query_name='product', to='shop.SalesAction', verbose_name='акции'),
        ),
    ]
