# Generated by Django 3.2.12 on 2025-06-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0240_auto_20250302_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='productintegration',
            name='notify_stock',
            field=models.BooleanField(default=False, verbose_name='требуется уведомление остатков'),
        ),
    ]
