# Generated by Django 3.2.12 on 2025-07-25 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0241_auto_20250606_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ozon_link',
            field=models.URLField(blank=True, max_length=512, verbose_name='ссылка на Озон'),
        ),
        migrations.AddField(
            model_name='product',
            name='wb_link',
            field=models.URLField(blank=True, max_length=512, verbose_name='ссылка на WB'),
        ),
    ]
