# Generated by Django 3.2.12 on 2025-09-30 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0242_auto_20250725_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Ссылка на видео-описание'),
        ),
    ]
