# Generated by Django 3.2.12 on 2025-11-01 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0243_auto_20250930_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='output_skip_categories',
            field=models.BooleanField(default=False, verbose_name='не выгражать категории'),
        ),
    ]
