# Generated by Django 3.2.12 on 2025-11-03 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0244_auto_20251101_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='output_paged',
            field=models.BooleanField(default=False, verbose_name='выгражать постранично'),
        ),
    ]
