# Generated by Django 3.2.12 on 2025-11-18 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0245_auto_20251103_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subname',
            field=models.CharField(blank=True, max_length=255, verbose_name='подзаголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='заголовок'),
        ),
    ]
