# Generated by Django 3.2.12 on 2025-12-01 14:09

from django.db import migrations, models
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0246_auto_20251118_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'новый заказ'), (1, 'принят в работу'), (2, 'ожидает подтверждения'), (4, 'комплектуется'), (8, 'отменен'), (16, 'заморожен'), (32, 'передан в другой магазин'), (64, 'собран'), (128, 'сервис'), (1024, 'доставляется'), (2048, 'доставлен'), (256, 'доставлен в магазин'), (512, 'передан в службу доставки'), (4096, 'консультация'), (8192, 'проблема'), (33554432, 'возвращается'), (67108864, 'не востребован'), (16384, 'завершён'), (251658240, 'выполнен')], db_index=True, default=0, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, db_index=True, help_text='код 1С', max_length=20, verbose_name='код товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='partnumber',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='артикул'),
        ),
    ]
