# Generated by Django 3.2.12 on 2025-12-01 14:10

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0247_auto_20251201_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='categories',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='adverts', related_query_name='advert', to='shop.Category', verbose_name='категории'),
        ),
    ]
