# Generated by Django 4.2.18 on 2026-04-26 18:10

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0248_advert_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='включена'),
        ),
    ]
