# Generated by Django 4.2.18 on 2026-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0249_integration_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, upload_to='addverts', verbose_name='изображение'),
        ),
    ]
