# Generated by Django 4.2.18 on 2026-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0250_advert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='big_image',
            field=models.ImageField(blank=True, upload_to='posters', verbose_name='больщое изображение'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, upload_to='posters', verbose_name='изображение'),
        ),
    ]
