# Generated by Django 4.2.18 on 2026-06-16 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0251_advert_big_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productintegration',
            name='meta',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
