# Generated by Django 4.2.18 on 2026-07-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0252_productintegration_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_prefix',
            field=models.TextField(blank=True, verbose_name='Описание типа (feed)'),
        ),
    ]
