# Generated by Django 4.2.18 on 2026-07-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0253_product_type_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена, руб')),
                ('pct_discount', models.PositiveSmallIntegerField(default=0, verbose_name='скидка, %')),
                ('val_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='скидка, руб')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', related_query_name='price', to='sites.site', verbose_name='сайт')),
            ],
            options={
                'verbose_name': 'цена товара',
                'verbose_name_plural': 'цены товаров',
                'unique_together': {('product', 'site')},
            },
        ),
    ]
