# Generated by Django 4.2.18 on 2026-07-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0254_create_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='cur_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена, вал'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_prices', related_query_name='site_price', to='shop.product'),
        ),
    ]
