# Generated by Django 4.2.18 on 2026-08-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0255_productprice_cur_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', to='sites.site', verbose_name='сайты'),
        ),
    ]
