# Generated by Django 4.2.18 on 2026-08-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0257_alter_act_id_alter_actorder_id_alter_advert_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorites',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('product', 'user', 'site')},
        ),
    ]
