# Generated by Django 4.2.18 on 2026-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0258_favorites_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.CharField(blank=True, max_length=512, verbose_name='сертификат'),
        ),
    ]
