# Generated by Django 4.2.18 on 2026-09-10 09:29

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0259_product_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='vat_rate',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Без НДС'), (2, 'НДС по ставке 0%'), (7, 'НДС по ставке 5%'), (8, 'НДС по ставке 7%'), (3, 'НДС по ставке 10%'), (4, 'НДС по ставке 20%'), (11, 'НДС по ставке 22%')], null=True, verbose_name='ставка НДС'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='manager',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_%(class)s', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
